version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 10s
      timeout: 5s
      retries: 5
  sender: 
    container_name: sender
    image: sender-dev
    build: 
      context: ./sender
      dockerfile: ../docker/Dockerfile.nestjs
      target: development
    volumes:
      - ./sender:/app
    ports: 
      - 3000:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: pnpm start:dev
  receiver: 
    container_name: receiver
    image: receiver-dev
    build: 
      context: ./receiver
      dockerfile: ../docker/Dockerfile.nestjs
      target: development
    volumes:
      - ./receiver:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: pnpm start:dev